#!/usr/bin/env python3
"""
generate_unicode_to_sjis.py
unicode_to_sjis.hpp を自動生成するスクリプト
データソース: Python標準codec cp932
"""
import os

def generate():
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "unicode_to_sjis.hpp")
    entries = []  # (unicode_codepoint, sjis_bytes)

    for cp in range(0x0080, 0x10000):
        try:
            char = chr(cp)
            encoded = char.encode('cp932')
            entries.append((cp, encoded))
        except (UnicodeEncodeError, UnicodeDecodeError):
            pass

    lines = []
    lines.append("// unicode_to_sjis.hpp")
    lines.append("// Auto-generated by generate_unicode_to_sjis.py")
    lines.append("// DO NOT EDIT MANUALLY")
    lines.append("#pragma once")
    lines.append("#if __cplusplus > 201703L")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace utf8_sjis {")
    lines.append("namespace detail {")
    lines.append("")
    lines.append("struct unicode_to_sjis_ret_t {")
    lines.append("    unsigned char byte[2]; // byte[0]: 1バイト目, byte[1]: 2バイト目")
    lines.append("    unsigned char num;     // 0: 変換不可, 1: 1バイト, 2: 2バイト")
    lines.append("};")
    lines.append("")
    lines.append("consteval unicode_to_sjis_ret_t unicode_to_sjis(uint32_t cp)")
    lines.append("{")
    lines.append("    switch (cp) {")

    for cp, b in entries:
        if len(b) == 1:
            lines.append(
                f"    case 0x{cp:04X}: return {{ {{ 0x{b[0]:02X}, 0x00 }}, 1 }};"
            )
        elif len(b) == 2:
            lines.append(
                f"    case 0x{cp:04X}: return {{ {{ 0x{b[0]:02X}, 0x{b[1]:02X} }}, 2 }};"
            )

    lines.append("    default:         return { { 0x00, 0x00 }, 0 };")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace detail")
    lines.append("} // namespace utf8_sjis")
    lines.append("")
    lines.append("#endif // __cplusplus > 201703L")
    lines.append("")

    output = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"生成完了: {len(entries)} エントリ")

    # 内容確認
    one_byte = sum(1 for _, b in entries if len(b) == 1)
    two_byte = sum(1 for _, b in entries if len(b) == 2)
    print(f"  1バイト文字: {one_byte} エントリ")
    print(f"  2バイト文字: {two_byte} エントリ")

if __name__ == "__main__":
    generate()
